### ISSUE TITLE
Add `onSuccess` callback for GET requests

### ISSUE THREAD

**Issue by mikespencer** [meetup/meetup-web-platform#207]
GET requests don't seem to accept an `onSuccess` callback like POST or DELETE requests do. Can we add this functionality? For example:

```js

function sortColumnSuccess({ queries, responses }) {
	return {
		type: 'SORT_COLUMN_API_SUCCESS',
		payload: { queries, responses }
	};
}

function sortColumn(params) {
	const {
		network,
		desc,
		order
	} = params;

	return {
		type: 'API_REQUEST',
		payload: [
			{
				ref: 'members',
				type: 'members',
				endpoint: `pro/${network.urlname}/members`,
				params: {
					desc,
					order,
					page: 20
				},
				onSuccess: sortColumnSuccess
			}
		],
		meta: {}
	};
}
```

The use case for this is that we need to be able to handle different api requests for the same set of data differently (eg: pagination, sorting, filtering, etc on the same set of data from the same api endpoint). Being able to do this based on the action type will make life much easier than having to create a custom ref for each situation.

**Comment by eilinora** [comment]
I think a reducer should be able to get you what your going for... as it is the middle man between the visual and the api success

**Comment by mikespencer** [comment]
How can we differentiate between different api successes in the reducer when the type is always `API_SUCCESS`?

**Comment by eilinora** [comment]
You use the REF from the request to differentiate results

**Comment by eilinora** [comment]
e.g. https://github.com/meetup/mup-web/blob/938b1e638fa4d8dbeb61c0847b72953e9148918c/src/app/group/communication/comments/commentsReducer.js#L86

**Comment by mikespencer** [comment]
That's exactly what I'd like to avoid... isn't the ref supposed to be used to define the key in state that the api response is stored in? Being able to define a specific action type for this would make things much cleaner in the reducer. Basically I need to be able to trigger a different action for a different behaviour on the same set of data under the same ref. Is there a reason that this is possible in a POST and DELETE but not in a GET? It seems much more scalable and less complicated/hacky to be able to perform different state changes based on different action types...

**Comment by eilinora** [comment]
I would comment on https://github.com/meetup/meetup-web-platform/pull/186/files#diff-a3a84e27f69b628e5e34b349545f38bdR91

This is a refactor that would check for errors and could include custom onSuccess

**Comment by mmcgahan** [comment]
I'm actually hoping to remove both the POST middleware and DELETE middleware because I think they provide functionality that could be handled more simply by a basic `API_REQUEST` action with a `Query` object that specifies whether it is a get, post, or delete.

The simplicity of _every_ `API_REQUEST` yielding a distinct `API_SUCCESS` or `API_ERROR` makes data fetching easier to understand because it's more predictable, and like Lori mentioned, reducers are designed to inspect each action to determine whether that action should affect the state they are responsible for. I think the uncertainty arises from treating `state.app` as _the_ reference for all current app data, when it really is just a place to store the most recently-requested API responses in a coherent/consistent way. From the platform's perspective, each query with the same `ref` is a request to update `state.app[ref]` to the return value.

If you want to extend the way that API_SUCCESS populates state, you'll need to write your own reducer in either the current system or the one proposed - listening for a custom `onSuccess` action and listening for a particular `API_SUCCESS` payload both have that requirement, so I'd argue there's not a lot of value in generating anything other than `API_SUCCESS` when your reducer is going to have to inspect your custom action in a similar way with a custom `onSuccess`.

In the `sortColumnSuccess` above, the reducer would probably look something like:

```js
import SORT_COLUMN_SUCCESS from './actions/sortColumn';
const tableReducer = (state, action) => {
  if (action.type === SORT_COLUMN_SUCCESS) {
    const response = action.payload.responses[0];  // assume response[COLUMN_QUERY_REF] exists
    const newState = ...;  // calculate new state from existing state + new response
    return newState;
  }
  return state;
};
```

The same functionality can be achieved in the current system with

```js
import COLUMN_QUERY_REF from './columnQuery';
const tableReducer = (state, action) => {
  if (action.type === 'API_SUCCESS') {
    const response = action.payload.responses.find(r => r[COLUMN_QUERY_REF]);
    if (!response) { return state; }
    const newState = ...;  // calculate new state from existing state + new response
    return newState;
  }
  return state;
};
```

I would argue that the complexity cost of the second option is less than the cost of writing a custom action creator for each custom `onSuccess` handler. In addition, PR #186 will make the 'standard' solution even simpler, with no `.find` and no escape hatch `if` block:

```js
import COLUMN_QUERY_REF from './columnQuery';
const tableReducer = (state, action) => {
  if (action.type === 'API_SUCCESS' &&
    action.payload.response.ref === COLUMN_QUERY_REF) {
    const response = action.payload.response;
    const newState = ...;   // calculate new state from existing state + new response
    return newState;
  }
  return state;
};
```

At that point, the difference between a custom `onSuccess` handler and the 'standard' implementation is that the 'standard' implementation requires checking for two properties of the `action`, whereas the custom `onSuccess` reducer only needs to check one `action` property at the cost of having an additional actionCreator function.

**Comment by mmcgahan** [comment]
Also, check out the slides from my conference talk about the query system, with some hints as to the direction I'd like to go with it: https://docs.google.com/presentation/d/1Co1awgbVT0S-2srKqfe7wtbnbiOv26mEHy1TaHIPdhE/edit?usp=sharing

I think I'll be able to share this talk at the Web Eng meeting on Tuesday

**Comment by sadafie** [comment]
Ping. Any updates on the issue? Status?

**Comment by mmcgahan** [comment]
`onSuccess` is now deprecated for all request methods - recommended solution is to watch for updates in `state.api[YOUR_QUERY]` when any request returns
