### ISSUE TITLE
Upgrade NR nodejs agent to v5

### ISSUE THREAD

**Issue by chenrui333** [meetup/meetup-web-platform#598]
Previously I have upgraded the [NR agent to v4](https://github.com/meetup/meetup-web-platform/pull/549) (because `distributed tracing` feature required the nodejs agent version >= `v4.7.0`).

Now, the nodejs agent version has been bumped into [v5.3.0](https://github.com/newrelic/node-newrelic/releases), it would be good to keep updated the NR nodejs agent.

I will think about upgrade the agent jar on the microservice side as well.

**Comment by chenrui333** [comment]
The features for the agent jar is listed in here:
https://github.com/newrelic/node-newrelic/blob/master/NEWS.md

**Comment by mmcgahan** [comment]
Thanks for raising the issue. I don't think we have many eyes on GH Issues at the moment, so it's probably better to go through the recommended channels = #web-platform-ask and/or Jira and/or Sean so that this work can be scheduled. I'll take it from here for this one - will try to get this done next sprint.

Just out of curiosity, there are lots of packages that we should upgrade, but is there a particular feature that you're needing to use in the latest NR agent?

**Comment by mmcgahan** [comment]
https://meetup.atlassian.net/browse/WP-1028

**Comment by mmcgahan** [comment]
closing in favor of Jira ticket
